title: Achilles
description: An advanced Java Object Mapper/Query DSL generator for Cassandra
google_analytics: UA-57227729-1
show_downloads: true
theme: jekyll-theme-dinky

gems:
  - jekyll-mentions
